title: El Sentido de la Vida
description: Wargame de introducción a Linux
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one